version: "3.8"

services:
  zomboid:
    build: .
    container_name: zomboid_server
    restart: unless-stopped
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "8766:8766/udp"
      - "8767:8767/udp"
    volumes:
      - ./config/venizao.ini:/data/venizao.ini
      - ./config/venizao_SandboxVars.lua:/data/venizao_SandboxVars.lua
      - ./config/venizao_spawnpoints.lua:/data/venizao_spawnpoints.lua
      - ./config/venizao_spawnregions.lua:/data/venizao_spawnregions.lua
    command: ["/opt/pzserver/start-server.sh", "-servername", "venizao", "-adminpassword", "venizao", "-port", "16261"]
    environment:
      - STEAM_BETA=unstable
      - SERVER_NAME=venizao
      - SERVER_ADMIN_PASSWORD=tiririca123
      - SERVER_MAX_PLAYERS=32
      - SERVER_PUBLIC=true
      - SERVER_PORT=16261
    stdin_open: true
    tty: true
    networks:
      zomboid_net:
        ipv4_address: 172.30.0.2

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - SECRET_KEY=63af71d1ece4ad3645cdd7b2c12af265383b8253e9e5ee85a456cbf637251309
    networks:
      zomboid_net:
        ipv4_address: 172.30.0.3
      
networks:
  zomboid_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
  